CREATE TABLE [dbo].[ALL_ACTUALS_NAMED] (
    [ROW_KEY]             NVARCHAR (54)   NULL,
    [COMPANY_MEMBERKEY]   VARCHAR (2)     NOT NULL,
    [COMPANY]             VARCHAR (36)    NOT NULL,
    [DATNAME]             VARCHAR (5)     NOT NULL,
    [FUNCTIONAL_CURNCYID] CHAR (15)       NULL,
    [TRIPCODE]            VARCHAR (31)    NULL,
    [CATEGORY]            VARCHAR (255)   NULL,
    [PAID_BY]             VARCHAR (3)     NULL,
    [VENDOR_CODE]         VARCHAR (27)    NULL,
    [VENDOR_NAME]         CHAR (65)       NULL,
    [POSTINGUSER]         CHAR (15)       NOT NULL,
    [FISCALDATE]          NVARCHAR (8)    NULL,
    [ORGNET]              NUMERIC (20, 5) NULL,
    [FUNCNET]             NUMERIC (20, 5) NULL,
    [ACTINDX]             INT             NULL,
    [SEG1_COMPANY]        VARCHAR (7)     NULL,
    [SEG2_TERRITORY]      VARCHAR (7)     NULL,
    [SEG3_DEPT]           VARCHAR (7)     NULL,
    [SEG4_OFFICE]         VARCHAR (7)     NULL,
    [SEG5_MAIN]           VARCHAR (7)     NULL,
    [SEG5_SERV]           VARCHAR (7)     NULL,
    [ACTDESCR]            CHAR (51)       NULL,
    [JRNENTRY]            INT             NOT NULL,
    [TRXDATE]             DATETIME        NOT NULL,
    [REFRENCE]            CHAR (31)       NOT NULL,
    [DSCRIPTN]            CHAR (31)       NOT NULL,
    [SOURCDOC]            CHAR (11)       NOT NULL,
    [ORDOCNUM]            CHAR (21)       NOT NULL,
    [ORGNTSRC]            CHAR (15)       NOT NULL,
    [GLCURNCYID]          CHAR (15)       NOT NULL,
    [ORDBTAMT]            NUMERIC (19, 5) NOT NULL,
    [DEBITAMT]            NUMERIC (19, 5) NOT NULL,
    [ORCRDAMT]            NUMERIC (19, 5) NOT NULL,
    [CRDTAMNT]            NUMERIC (19, 5) NOT NULL,
    [ORPSTDDT]            DATETIME        NOT NULL,
    [CADNET]              NUMERIC (18, 5) NULL,
    [USDNET]              NUMERIC (18, 5) NULL,
    [VCHRNMBR]            CHAR (21)       NULL,
    [VENDORID]            CHAR (15)       NULL,
    [DOCTYPE]             SMALLINT        NULL,
    [DOCDATE]             DATETIME        NULL,
    [DOCNUMBR]            CHAR (21)       NULL,
    [DOCAMNT]             NUMERIC (19, 5) NULL,
    [CURTRXAM]            NUMERIC (19, 5) NULL,
    [DISTKNAM]            NUMERIC (19, 5) NULL,
    [DISCAMNT]            NUMERIC (19, 5) NULL,
    [DSCDLRAM]            NUMERIC (19, 5) NULL,
    [BACHNUMB]            CHAR (15)       NULL,
    [TRXSORCE]            CHAR (13)       NULL,
    [BCHSOURC]            CHAR (15)       NULL,
    [DISCDATE]            DATETIME        NULL,
    [DUEDATE]             DATETIME        NULL,
    [PORDNMBR]            CHAR (21)       NULL,
    [TEN99AMNT]           NUMERIC (19, 5) NULL,
    [WROFAMNT]            NUMERIC (19, 5) NULL,
    [DISAMTAV]            NUMERIC (19, 5) NULL,
    [TRXDSCRN]            CHAR (31)       NULL,
    [UN1099AM]            NUMERIC (19, 5) NULL,
    [BKTPURAM]            NUMERIC (19, 5) NULL,
    [BKTFRTAM]            NUMERIC (19, 5) NULL,
    [BKTMSCAM]            NUMERIC (19, 5) NULL,
    [VOIDED]              TINYINT         NULL,
    [HOLD]                TINYINT         NULL,
    [CHEKBKID]            CHAR (15)       NULL,
    [DINVPDOF]            DATETIME        NULL,
    [PPSAMDED]            NUMERIC (19, 5) NULL,
    [PGRAMSBJ]            SMALLINT        NULL,
    [GSTDSAMT]            NUMERIC (19, 5) NULL,
    [POSTEDDT]            DATETIME        NULL,
    [PTDUSRID]            CHAR (15)       NULL,
    [MODIFDT]             DATETIME        NULL,
    [MDFUSRID]            CHAR (15)       NULL,
    [PYENTTYP]            SMALLINT        NULL,
    [CARDNAME]            CHAR (15)       NULL,
    [PRCHAMNT]            NUMERIC (19, 5) NULL,
    [TRDISAMT]            NUMERIC (19, 5) NULL,
    [MSCCHAMT]            NUMERIC (19, 5) NULL,
    [FRTAMNT]             NUMERIC (19, 5) NULL,
    [TAXAMNT]             NUMERIC (19, 5) NULL,
    [TTLPYMTS]            NUMERIC (19, 5) NULL,
    [CURNCYID]            CHAR (15)       NULL,
    [PYMTRMID]            CHAR (21)       NULL,
    [SHIPMTHD]            CHAR (15)       NULL,
    [TAXSCHID]            CHAR (15)       NULL,
    [PCHSCHID]            CHAR (15)       NULL,
    [FRTSCHID]            CHAR (15)       NULL,
    [MSCSCHID]            CHAR (15)       NULL,
    [PSTGDATE]            DATETIME        NULL,
    [DISAVTKN]            NUMERIC (19, 5) NULL,
    [CNTRLTYP]            SMALLINT        NULL,
    [NOTEINDX]            NUMERIC (19, 5) NULL,
    [PRCTDISC]            SMALLINT        NULL,
    [RETNAGAM]            NUMERIC (19, 5) NULL,
    [ICTRX]               DATETIME        NULL,
    [TAX_DATE]            DATETIME        NULL,
    [PRCHDATE]            DATETIME        NULL,
    [CORRCTN]             DATETIME        NULL,
    [SIMPLIFD]            TINYINT         NULL,
    [BNKRCAMT]            NUMERIC (19, 5) NULL,
    [APLYWITH]            TINYINT         NULL,
    [ELECTRONIC]          TINYINT         NULL,
    [ECTRX]               TINYINT         NULL,
    [DOCPRINTED]          TINYINT         NULL,
    [TAXINVREQD]          TINYINT         NULL,
    [VNDCHKNM]            CHAR (65)       NULL,
    [BACKOUTTRADEDISC]    NUMERIC (19, 5) NULL,
    [CBVAT]               TINYINT         NULL,
    [VADCDTRO]            CHAR (15)       NULL,
    [TEN99TYPE]           SMALLINT        NULL,
    [TEN99BOXNUMBER]      SMALLINT        NULL,
    [DEX_ROW_TS]          DATETIME        NOT NULL,
    [DEX_ROW_ID]          INT             NOT NULL,
    [CAD_XCHGRATE]        NUMERIC (19, 7) NULL,
    [USD_XCHGRATE]        NUMERIC (19, 7) NULL,
    [PROJ]                VARCHAR (50)    NULL
);

