CREATE TABLE [dbo].[ETL_ERROR_LOG] (
    [ID]            BIGINT         IDENTITY (1, 1) NOT NULL,
    [CREATE_DATE]   DATETIME       NULL,
    [CREATE_USER]   VARCHAR (50)   NULL,
    [PROCESS_NAME]  VARCHAR (50)   NULL,
    [ERROR_NUMBER]  VARCHAR (50)   NULL,
    [ERROR_MESSAGE] VARCHAR (5000) NULL,
    CONSTRAINT [PK_ETL_ERROR_LOG] PRIMARY KEY CLUSTERED ([ID] ASC)
);

